### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by hzoo** [hzoo/babel-jscs#2]
Not sure why but

```js
  it("flow type", function () {
    verifyAndAssertMessages(
      "var x; type SomeNewType = any;",
      {},
      []
    );
  });
```

Is failing https://travis-ci.org/hzoo/babel-jscs/jobs/65972862

The error message from jscs isn't helpful: `AssertionError: Unable to add an error, `line` should be a number greater than 0 but undefined given`

After console logging the actual errors from `file.getParseErrors()` I'm getting

`[TypeError: Cannot call method 'isSequenceExpression' of undefined]`.

@sebmck any ideas? Also no issue from `babel-eslint`.

**Comment by sebmck** [comment]
Do you have the whole stack trace?

**Comment by hzoo** [comment]
Just what's in travis which doesn't really help. It's basically just calling the parse method of esprima.

```js
try {
        this._tree = parseJavaScriptSource(this._source, params.esprima, params.esprimaOptions);
    } catch (e) {
        this._parseErrors.push(e);
    }
```
`parseJavaScriptSource` calls `tree = esprima.parse(source, finalEsprimaOptions);` which would use the babel-jscs parse method. It fails pushes the message above `[TypeError: Cannot call method 'isSequenceExpression' of undefined]`

Looks like it was passing in https://travis-ci.org/hzoo/babel-jscs/builds/64191732 with babel 5.4.7 and failed after updating to 5.5.5.

**Comment by hzoo** [comment]
Ok in `removal-hooks` https://github.com/babel/babel/blob/4aec242979468379401ba4fa8a4748d0bcde6fa6/src/babel/traversal/path/lib/removal-hooks.js#L73-L95

```js
function (self, parent) {
    if (parent.isSequenceExpression() && parent.node.expressions.length === 1) {
      // (node, NODE);
      // we've just removed the second element of a sequence expression so let's turn that sequence
      // expression into a regular expression
      parent.replaceWith(parent.node.expressions[0]);
      return true;
    }
  },
```

parent is undefined and causes the issue on `parent.isSequenceExpression()`. I can fix by just adding `parent && ...` in the `IfStatement` for both functions but don't know know if that's what's needed.

**Comment by sebmck** [comment]
It's only effecting `babel-jscs` and not `babel-eslint` right?

**Comment by hzoo** [comment]
Yeah only `babel-jscs` I reran a PR in babel-eslint and didn't get errors.

**Comment by sebmck** [comment]
Hesitant to add a check for `parent` since it’s likely something else that’s actually breaking.

**Comment by hzoo** [comment]
Yeah will investigate some more.

**Comment by hzoo** [comment]
Ok haha I tried using the `babel-eslint` package and replaced only the `monkeypatch` method to work for jscs and it seems to be working! So whatever different code `babel-jscs` had was triggering `removal-hooks` to be run. =/

**Comment by hzoo** [comment]
Ok I did a diff of the files - `index.js` is basically the same other than change the module paths for `monkeypatch as well as all the escope changes since jscs doesn't need to care about scope (`no-undef`  and `no-unused-vars` although it not bad just unncessary. `acorn-to-esprima.js` is also basically the same except that in the jscs one we are removing the flow types still with

```js
if (this.isFlow()) {
      return this.dangerouslyRemove();
    }
```

If I add that back into `babel-eslint`, of course all the flow tests will fail now. But if we weren't parsing flow it would also get the same error
`Error: Expected 0 message(s), got 1 [{"fatal":true,"severity":2,"message":"Cannot call method 'isSequenceExpression' of undefined"}]`

So one solution is to do the parent check since the error would of occurred in `babel-eslint` (I think because remove would then cause parent to be undefined since the only code in that test is a `type`).

But now that I'm looking at it I shouldn't be using `this.dangerouslyRemove()` anyway. And there isn't an problem on jscs with just removing that statement.

**Comment by hzoo** [comment]
@sebmck yay passed - https://travis-ci.org/hzoo/babel-jscs/builds/66154539 - I guess `remove` is dangerous :smile:
